#!/bin/bash  
echo "This is a shell script" 

VAR1="source /opt/ros/kinetic/setup.bash; source /home/aimove/ros/urdriver_ws/devel/setup.bash; source /home/aimove/ros/ur_ws/devel/setup.bash; source /home/aimove/ros/jogarm_ws/devel/setup.bash"

xterm -hold -title "master" -e "$VAR1; roslaunch ur_modern_driver ur3_bringup.launch robot_ip:=10.0.0.9" &
sleep 1
xterm -hold -title "openpose" -e "$VAR1; rosrun ur_modern_driver angle_publisher.py" &






